version: '3.8'
services:
  neo4j:
    image: neo4j:5-community
    ports:
      - "7474:7474"  # HTTP interface
      - "7687:7687"  # Bolt protocol (for the Python driver)
    environment:
      - NEO4J_AUTH=neo4j/password123  # Set a secure password
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  neo4j_data:
  redis_data: